site_name: "Open-Source Startup Services Directory"
nav:
  - "Quick-Start Guide":
      - "Community Edition": quick-start-guide/community-edition.md
      - "Enterprise Edition": quick-start-guide/enterprise-edition.md
  - "Installation":
      - "Requirements": installation/requirements.md
      - "Architecture": installation/architecture.md
      - "Kubernetes": installation/kubernetes.md
      - "Kubernetes Operator": installation/kubernetes-operator.md
      - "OpenShift": installation/openshift.md
      - "Docker": installation/docker.md
      - "Docker Swarm": installation/docker-swarm.md
      - "Ubuntu & Debian": installation/ubuntu-debian.md
      - "RHEL & CentOS": installation/rhel-centos.md
      - "Performance Impact": installation/performance-impact.md
  - "Configuration":
      - "Configuration": configuration/configuration.md
      - "Authentication": configuration/authentication.md
      - "Role-Based Access Control": configuration/role-based-access-control.md
      - "Prometheus": configuration/prometheus.md
      - "ClickHouse": configuration/clickhouse.md
      - "Multi-tenancy": configuration/multi-tenancy.md
      - "Database": configuration/database.md
      - "High Availability": configuration/high-availability.md
      - "Application Categories": configuration/application-categories.md
      - "Custom Applications": configuration/custom-applications.md
  - "Alerting":
      - "Service Level Objective (SLO) monitoring": alerting/slo-monitoring.md
      - "Incidents": alerting/incidents.md
      - "Slack": alerting/slack.md
      - "Microsoft Teams": alerting/microsoft-teams.md
      - "Pagerduty": alerting/pagerduty.md
      - "Opsgenie": alerting/opsgenie.md
      - "Webhook": alerting/webhook.md
  - "Log Monitoring":
      - "Overview": log-monitoring/overview.md
  - "Distibuted Tracing":
      - "Overview": distributed-tracing/overview.md
      - "eBPF-based tracing": distributed-tracing/ebpf-based-tracing.md
      - "OpenTelemetry for Go": distributed-tracing/opentelemetry-go.md
      - "OpenTelemetry for Java": distributed-tracing/opentelemetry-java.md
      - "OpenTelemetry for Python": distributed-tracing/opentelemetry-python.md
  - "Inspections":
      - "Overview": inspections/overview.md
      - "Service Level Objectives (SLOs)": inspections/slo.md
      - "Instances": inspections/instances.md
      - "CPU": inspections/cpu.md
      - "Memory": inspections/memory.md
      - "Storage": inspections/storage.md
      - "Network": inspections/network.md
      - "Logs": inspections/logs.md
      - "JVM": inspections/jvm.md
      - ".NET": inspections/dotnet.md
      - "Python": inspections/python.md
      - "Postgres": inspections/postgres.md
      - "Mongodb": inspections/mongodb.md
      - "MySQL": inspections/mysql.md
      - "Memcached": inspections/memcached.md
      - "Redis": inspections/redis.md
      - "Deployment tracking": inspections/deployment-tracking.md
  - "Profiling":
      - "Overview": profiling/overview.md
  - "Cloud Cost Monitoring":
      - "Overview": cloud-cost-monitoring/overview.md
  - "Misc":
      - "Anonymous usage statistics": misc/anonymous-usage-statistics.md


theme:
  name: 'material'