site_name: "Open-Source-Services-Directory"
docs_dir: docs
theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Poppins"
    code: "Poppins Mono"
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant