site_name: "Open-Source Startup Services Directory"
nav:
  - Home: index.md
  - Categories:
    - Funding: categories/funding.md
    - Legal: categories/legal.md
    - Marketing: categories/marketing.md
    - How To: categories/How To/how-to-start.md


theme:
  name: 'material'