name: Validate Docs-Only Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-only-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes outside docs/
        run: |
          # Determine the base commit. For PRs, this compares head with base; for pushes, it compares the current commit to the previous one.
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
          else
            # Use git to compare the last commit to the current one
            BASE_SHA=$(git rev-parse HEAD~1)
            HEAD_SHA=$(git rev-parse HEAD)
          fi

          echo "Comparing changes from $BASE_SHA to $HEAD_SHA"

          # Get list of changed files.
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA")
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Loop through each file and verify it is under the docs/ directory.
          EXIT_CODE=0
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" != docs/* ]]; then
              echo "Error: File '$FILE' is outside of the docs/ directory."
              EXIT_CODE=1
            fi
          done

          if [ $EXIT_CODE -ne 0 ]; then
            echo "Validation failed: Only changes in the docs/ directory are allowed."
            exit 1
          else
            echo "Validation succeeded: All changes are within the docs/ directory."
          fi
